#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
from termcolor import colored

def try_me(age):
    me = 24
    if age < 0:
        answer = 'You are not born yet or you are cheating, then I guess you cheat'
    elif 0 < age < 24:
        answer = 'You are young'
    elif age > 24:
        answer = 'Hello grandpapa'
    
    return answer

if __name__ == '__main__':
    description = 'stkrgcp_description'
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('--age',
                        nargs='+',
                        help='list of coordinates',
                        required=False)
    parser.add_argument('--prod',
                        action='store_true',
                        default=False,
                        help='Example here')
    args = parser.parse_args()
    age = args.age
    print(age)
    answer = try_me(float(age[0]))
    print(colored("###### Age ######", "blue"))
    print(colored(answer, "red"))


